import React, { useContext } from 'react';
import { ThemeContext } from '../context/ThemeContext';
import Feautures from './Features';

const About = () => {
  const { isDarkMode } = useContext(ThemeContext);

  return (
    <div className={isDarkMode ? "hero-body fadedark-mode" : "hero-body"}>
      <div className="hero">
        <div className="section">
          <div className='has-text-centered'>
            <h1 className="title">Nuvo App</h1>
            <h2 className="subtitle">Know more about our ecosystem</h2>
            <p className='section has-text-centered subtitle'>Transforming Digital Identity and Decentralized Economy

            At the forefront of the technological revolution, the Nuvo Project emerges as a beacon of innovation in the realm of solutions for the decentralized community. Our mission is to harness the potential of blockchain technology to create a digital ecosystem where identity, ownership, and transactions are secure, transparent, and accessible to all.

            Focused on the creation of cutting-edge smart contracts, the core of our work revolves around bringing NFTs (Non-Fungible Tokens) to life, revolutionizing the way users interact with the digital world. Our platform enables users to own unique and non-transferable digital products that not only reflect their digital identity but also grant them a range of exclusive benefits.

            The NFTs generated by the Nuvo Project are not only symbols of digital ownership but also gateways to a world of opportunities. From validating digital identity to obtaining and claiming rewards, discounts, airdrops, and third-party benefits, our users enjoy an unparalleled digital experience where each interaction becomes an opportunity to maximize their potential.

            In an increasingly digitized world, security and privacy are our top priorities. That's why, at the Nuvo Project, we are committed to ensuring the integrity of every transaction and the protection of our users' data, using state-of-the-art technologies and robust security practices.

            In summary, the Nuvo Project represents the future of digital identity and the decentralized economy. With our dedication to innovation, transparency, and security, we are building a more inclusive and empowered digital world for all. Join us on our journey towards a brighter and more equitable digital tomorrow. </p>
          </div>
        </div>
      </div>
      <Feautures />
    </div>
  );
};

export default About;
