export const cspConfig = {
  directives: {
    'default-src': ["'self'"],
    'connect-src': [
      "'self'",
      'data:',
      'https://api.dodoex.io',
      'https://*.nftstorage.link',
      'https://polygon-mainnet.g.alchemy.com',
      'wss://polygon-mainnet.g.alchemy.com',
      "https://api.pinata.cloud",
      "https://gateway.pinata.cloud",
      "https://ipfs.io",
      "https://cloudflare-ipfs.com",
      "https://dweb.link",
      "https://*.ipfs.dweb.link",
      "https://*.ipfs.cf-ipfs.com",
      "https://*.ipfs.nftstorage.link", 
      "https://nftstorage.link",
      "https://*.ipfs.w3s.link",
      "https://w3s.link",
      "https://ipfs.cf-ipfs.com",
      "https://gateway.ipfs.io",
      'https://*.dodoex.io',
      'https://*.alchemy.com',
      'wss://*.alchemy.com',
      'https://polygon-rpc.com',
      'https://rpc-mainnet.matic.network',
      'https://matic-mainnet.chainstacklabs.com',
      'https://rpc-mumbai.maticvigil.com',
      'https://matic-mumbai.chainstacklabs.com',
      'https://*.vercel.app',
      'https://*.vercel.com',
      'https://vercel.live',
      'https://nuvos.app',
      'https://*.nuvos.app',
      process.env.NODE_ENV === 'development' ? 'ws://localhost:*' : null,
      process.env.NODE_ENV === 'development' ? 'wss://localhost:*' : null
    ].filter(Boolean),
    'img-src': [
      "'self'",
      'data:',
      'blob:',
      'https://images.dodoex.io',
      'https://*.nftstorage.link',
      'https://*.dodoex.io',
      'https://static.okx.com',
      'https://polygonscan.com',
      'https://*.googleapis.com',
      'https://gateway.pinata.cloud',
      'https://ipfs.io',
      'https://cloudflare-ipfs.com',
      'https://dweb.link',
      'https://*.ipfs.dweb.link',
      'https://*.ipfs.cf-ipfs.com',
      'https://ipfs.cf-ipfs.com',
      'https://*.ipfs.nftstorage.link',
      'https://nftstorage.link',
      'https://*.ipfs.w3s.link',
      'https://w3s.link',
      'https://gateway.ipfs.io',
      'https://*.vercel.app',
      'https://*.arweave.net',
      'https://*.infura-ipfs.io',
      'https://cryptologos.cc',
      'https://cf-ipfs.com',
      'https://ipfs.fleek.co',
      'https://hardbin.com',
      'https://ipfs.globalupload.io',
      'https://nuvos.app',
      'https://*.nuvos.app'
    ],
    'script-src': [
      "'self'",
      "'unsafe-inline'",
      "'unsafe-eval'",
      'https://*.firebaseapp.com',
      'https://apis.google.com',
      'https://*.vercel.app',
      'https://*.vercel.com',
      'https://vercel.live'
    ],
    'style-src': ["'self'", "'unsafe-inline'"],
    'frame-src': [
      "'self'",
      'https://widget.dodoex.io',
      'https://*.firebaseapp.com',
      'https://*.vercel.app',
      'https://*.vercel.com'
    ]
  }
};
